name: Android CI Debug

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jar

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/ADOFAI-Helper-1.0-SNAPSHOT.jar
